package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Certificado generated by hbm2java
 */
public class Certificado  implements java.io.Serializable {


     private Integer codCertificado;
     private String nombreCertificado;
     private Date fechaEmision;
     private String descripcion;
     private Set<Modelo> modelos = new HashSet<Modelo>(0);
     private Set<TrabajadorHasCertificado> trabajadorHasCertificados = new HashSet<TrabajadorHasCertificado>(0);

    public Certificado() {
    }

	
    public Certificado(String nombreCertificado, Date fechaEmision, String descripcion) {
        this.nombreCertificado = nombreCertificado;
        this.fechaEmision = fechaEmision;
        this.descripcion = descripcion;
    }
    public Certificado(String nombreCertificado, Date fechaEmision, String descripcion, Set<Modelo> modelos, Set<TrabajadorHasCertificado> trabajadorHasCertificados) {
       this.nombreCertificado = nombreCertificado;
       this.fechaEmision = fechaEmision;
       this.descripcion = descripcion;
       this.modelos = modelos;
       this.trabajadorHasCertificados = trabajadorHasCertificados;
    }
   
    public Integer getCodCertificado() {
        return this.codCertificado;
    }
    
    public void setCodCertificado(Integer codCertificado) {
        this.codCertificado = codCertificado;
    }
    public String getNombreCertificado() {
        return this.nombreCertificado;
    }
    
    public void setNombreCertificado(String nombreCertificado) {
        this.nombreCertificado = nombreCertificado;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Modelo> getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set<Modelo> modelos) {
        this.modelos = modelos;
    }
    public Set<TrabajadorHasCertificado> getTrabajadorHasCertificados() {
        return this.trabajadorHasCertificados;
    }
    
    public void setTrabajadorHasCertificados(Set<TrabajadorHasCertificado> trabajadorHasCertificados) {
        this.trabajadorHasCertificados = trabajadorHasCertificados;
    }




}


