package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Componente generated by hbm2java
 */
public class Componente  implements java.io.Serializable {


     private Integer codComponente;
     private String partNumber;
     private String nombre;
     private String estado;
     private Set<EquipoHasComponente> equipoHasComponentes = new HashSet<EquipoHasComponente>(0);
     private Set<Parte> partes = new HashSet<Parte>(0);

    public Componente() {
    }

	
    public Componente(String partNumber, String nombre, String estado) {
        this.partNumber = partNumber;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Componente(String partNumber, String nombre, String estado, Set<EquipoHasComponente> equipoHasComponentes, Set<Parte> partes) {
       this.partNumber = partNumber;
       this.nombre = nombre;
       this.estado = estado;
       this.equipoHasComponentes = equipoHasComponentes;
       this.partes = partes;
    }
   
    public Integer getCodComponente() {
        return this.codComponente;
    }
    
    public void setCodComponente(Integer codComponente) {
        this.codComponente = codComponente;
    }
    public String getPartNumber() {
        return this.partNumber;
    }
    
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<EquipoHasComponente> getEquipoHasComponentes() {
        return this.equipoHasComponentes;
    }
    
    public void setEquipoHasComponentes(Set<EquipoHasComponente> equipoHasComponentes) {
        this.equipoHasComponentes = equipoHasComponentes;
    }
    public Set<Parte> getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set<Parte> partes) {
        this.partes = partes;
    }




}


