package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int codDepartamento;
     private String nombreDepartamento;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);

    public Departamento() {
    }

	
    public Departamento(int codDepartamento, String nombreDepartamento) {
        this.codDepartamento = codDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(int codDepartamento, String nombreDepartamento, Set<Provincia> provincias) {
       this.codDepartamento = codDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.provincias = provincias;
    }
   
    public int getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(int codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


