package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private DetalleFacturaId id;
     private Equipo equipo;
     private Factura factura;
     private Garantia garantia;
     private Date fechaFinGarantia;

    public DetalleFactura() {
    }

	
    public DetalleFactura(DetalleFacturaId id, Equipo equipo, Factura factura) {
        this.id = id;
        this.equipo = equipo;
        this.factura = factura;
    }
    public DetalleFactura(DetalleFacturaId id, Equipo equipo, Factura factura, Garantia garantia, Date fechaFinGarantia) {
       this.id = id;
       this.equipo = equipo;
       this.factura = factura;
       this.garantia = garantia;
       this.fechaFinGarantia = fechaFinGarantia;
    }
   
    public DetalleFacturaId getId() {
        return this.id;
    }
    
    public void setId(DetalleFacturaId id) {
        this.id = id;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Garantia getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(Garantia garantia) {
        this.garantia = garantia;
    }
    public Date getFechaFinGarantia() {
        return this.fechaFinGarantia;
    }
    
    public void setFechaFinGarantia(Date fechaFinGarantia) {
        this.fechaFinGarantia = fechaFinGarantia;
    }




}


