package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer codDireccion;
     private Distrito distrito;
     private String detalleDireccion;
     private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);
     private Set<ClienteNatural> clienteNaturals = new HashSet<ClienteNatural>(0);

    public Direccion() {
    }

	
    public Direccion(Distrito distrito, String detalleDireccion) {
        this.distrito = distrito;
        this.detalleDireccion = detalleDireccion;
    }
    public Direccion(Distrito distrito, String detalleDireccion, Set<Sucursal> sucursals, Set<Empresa> empresas, Set<Incidencia> incidencias, Set<ClienteNatural> clienteNaturals) {
       this.distrito = distrito;
       this.detalleDireccion = detalleDireccion;
       this.sucursals = sucursals;
       this.empresas = empresas;
       this.incidencias = incidencias;
       this.clienteNaturals = clienteNaturals;
    }
   
    public Integer getCodDireccion() {
        return this.codDireccion;
    }
    
    public void setCodDireccion(Integer codDireccion) {
        this.codDireccion = codDireccion;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getDetalleDireccion() {
        return this.detalleDireccion;
    }
    
    public void setDetalleDireccion(String detalleDireccion) {
        this.detalleDireccion = detalleDireccion;
    }
    public Set<Sucursal> getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set<Sucursal> sucursals) {
        this.sucursals = sucursals;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }
    public Set<ClienteNatural> getClienteNaturals() {
        return this.clienteNaturals;
    }
    
    public void setClienteNaturals(Set<ClienteNatural> clienteNaturals) {
        this.clienteNaturals = clienteNaturals;
    }




}


