package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private int codDistrito;
     private Provincia provincia;
     private String nombreDistrito;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Distrito() {
    }

	
    public Distrito(int codDistrito, Provincia provincia, String nombreDistrito) {
        this.codDistrito = codDistrito;
        this.provincia = provincia;
        this.nombreDistrito = nombreDistrito;
    }
    public Distrito(int codDistrito, Provincia provincia, String nombreDistrito, Set<Direccion> direccions) {
       this.codDistrito = codDistrito;
       this.provincia = provincia;
       this.nombreDistrito = nombreDistrito;
       this.direccions = direccions;
    }
   
    public int getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(int codDistrito) {
        this.codDistrito = codDistrito;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombreDistrito() {
        return this.nombreDistrito;
    }
    
    public void setNombreDistrito(String nombreDistrito) {
        this.nombreDistrito = nombreDistrito;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


