package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer codEmpresa;
     private Direccion direccion;
     private Location location;
     private String paginaWeb;

    public Empresa() {
    }

    public Empresa(Direccion direccion, Location location, String paginaWeb) {
       this.direccion = direccion;
       this.location = location;
       this.paginaWeb = paginaWeb;
    }
   
    public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }




}


