package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * EquipoHasComponenteId generated by hbm2java
 */
public class EquipoHasComponenteId  implements java.io.Serializable {


     private String numeroSerie;
     private int codComponente;

    public EquipoHasComponenteId() {
    }

    public EquipoHasComponenteId(String numeroSerie, int codComponente) {
       this.numeroSerie = numeroSerie;
       this.codComponente = codComponente;
    }
   
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public int getCodComponente() {
        return this.codComponente;
    }
    
    public void setCodComponente(int codComponente) {
        this.codComponente = codComponente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EquipoHasComponenteId) ) return false;
		 EquipoHasComponenteId castOther = ( EquipoHasComponenteId ) other; 
         
		 return ( (this.getNumeroSerie()==castOther.getNumeroSerie()) || ( this.getNumeroSerie()!=null && castOther.getNumeroSerie()!=null && this.getNumeroSerie().equals(castOther.getNumeroSerie()) ) )
 && (this.getCodComponente()==castOther.getCodComponente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumeroSerie() == null ? 0 : this.getNumeroSerie().hashCode() );
         result = 37 * result + this.getCodComponente();
         return result;
   }   


}


