package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private String numeroSerie;
     private Modelo modelo;
     private Set<EquipoHasComponente> equipoHasComponentes = new HashSet<EquipoHasComponente>(0);
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Equipo() {
    }

	
    public Equipo(String numeroSerie, Modelo modelo) {
        this.numeroSerie = numeroSerie;
        this.modelo = modelo;
    }
    public Equipo(String numeroSerie, Modelo modelo, Set<EquipoHasComponente> equipoHasComponentes, Set<Incidencia> incidencias, Set<DetalleFactura> detalleFacturas) {
       this.numeroSerie = numeroSerie;
       this.modelo = modelo;
       this.equipoHasComponentes = equipoHasComponentes;
       this.incidencias = incidencias;
       this.detalleFacturas = detalleFacturas;
    }
   
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public Set<EquipoHasComponente> getEquipoHasComponentes() {
        return this.equipoHasComponentes;
    }
    
    public void setEquipoHasComponentes(Set<EquipoHasComponente> equipoHasComponentes) {
        this.equipoHasComponentes = equipoHasComponentes;
    }
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


