package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int codEstado;
     private String nombreEstado;
     private Set<IncidenciaHasEstado> incidenciaHasEstados = new HashSet<IncidenciaHasEstado>(0);

    public Estado() {
    }

	
    public Estado(int codEstado, String nombreEstado) {
        this.codEstado = codEstado;
        this.nombreEstado = nombreEstado;
    }
    public Estado(int codEstado, String nombreEstado, Set<IncidenciaHasEstado> incidenciaHasEstados) {
       this.codEstado = codEstado;
       this.nombreEstado = nombreEstado;
       this.incidenciaHasEstados = incidenciaHasEstados;
    }
   
    public int getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(int codEstado) {
        this.codEstado = codEstado;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public Set<IncidenciaHasEstado> getIncidenciaHasEstados() {
        return this.incidenciaHasEstados;
    }
    
    public void setIncidenciaHasEstados(Set<IncidenciaHasEstado> incidenciaHasEstados) {
        this.incidenciaHasEstados = incidenciaHasEstados;
    }




}


