package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer codFactura;
     private Location location;
     private Date fechaCompra;
     private double costoTotal;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(Location location, Date fechaCompra, double costoTotal) {
        this.location = location;
        this.fechaCompra = fechaCompra;
        this.costoTotal = costoTotal;
    }
    public Factura(Location location, Date fechaCompra, double costoTotal, Set<DetalleFactura> detalleFacturas) {
       this.location = location;
       this.fechaCompra = fechaCompra;
       this.costoTotal = costoTotal;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getCodFactura() {
        return this.codFactura;
    }
    
    public void setCodFactura(Integer codFactura) {
        this.codFactura = codFactura;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public double getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(double costoTotal) {
        this.costoTotal = costoTotal;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


