package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private Integer codGarantia;
     private int tiempoGarantia;
     private String unidadTiempoGarantia;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Garantia() {
    }

	
    public Garantia(int tiempoGarantia, String unidadTiempoGarantia) {
        this.tiempoGarantia = tiempoGarantia;
        this.unidadTiempoGarantia = unidadTiempoGarantia;
    }
    public Garantia(int tiempoGarantia, String unidadTiempoGarantia, Set<DetalleFactura> detalleFacturas) {
       this.tiempoGarantia = tiempoGarantia;
       this.unidadTiempoGarantia = unidadTiempoGarantia;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getCodGarantia() {
        return this.codGarantia;
    }
    
    public void setCodGarantia(Integer codGarantia) {
        this.codGarantia = codGarantia;
    }
    public int getTiempoGarantia() {
        return this.tiempoGarantia;
    }
    
    public void setTiempoGarantia(int tiempoGarantia) {
        this.tiempoGarantia = tiempoGarantia;
    }
    public String getUnidadTiempoGarantia() {
        return this.unidadTiempoGarantia;
    }
    
    public void setUnidadTiempoGarantia(String unidadTiempoGarantia) {
        this.unidadTiempoGarantia = unidadTiempoGarantia;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


