package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GrDevolucion generated by hbm2java
 */
public class GrDevolucion  implements java.io.Serializable {


     private Integer codGrDevolucion;
     private ParteDevuelta parteDevuelta;
     private String numeroRemito;
     private String destinatario;
     private Date fechaDevolucion;
     private String puntoPartida;
     private String puntoLlegada;

    public GrDevolucion() {
    }

    public GrDevolucion(ParteDevuelta parteDevuelta, String numeroRemito, String destinatario, Date fechaDevolucion, String puntoPartida, String puntoLlegada) {
       this.parteDevuelta = parteDevuelta;
       this.numeroRemito = numeroRemito;
       this.destinatario = destinatario;
       this.fechaDevolucion = fechaDevolucion;
       this.puntoPartida = puntoPartida;
       this.puntoLlegada = puntoLlegada;
    }
   
    public Integer getCodGrDevolucion() {
        return this.codGrDevolucion;
    }
    
    public void setCodGrDevolucion(Integer codGrDevolucion) {
        this.codGrDevolucion = codGrDevolucion;
    }
    public ParteDevuelta getParteDevuelta() {
        return this.parteDevuelta;
    }
    
    public void setParteDevuelta(ParteDevuelta parteDevuelta) {
        this.parteDevuelta = parteDevuelta;
    }
    public String getNumeroRemito() {
        return this.numeroRemito;
    }
    
    public void setNumeroRemito(String numeroRemito) {
        this.numeroRemito = numeroRemito;
    }
    public String getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public String getPuntoPartida() {
        return this.puntoPartida;
    }
    
    public void setPuntoPartida(String puntoPartida) {
        this.puntoPartida = puntoPartida;
    }
    public String getPuntoLlegada() {
        return this.puntoLlegada;
    }
    
    public void setPuntoLlegada(String puntoLlegada) {
        this.puntoLlegada = puntoLlegada;
    }




}


