package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GrEnvio generated by hbm2java
 */
public class GrEnvio  implements java.io.Serializable {


     private Integer codGrEnvio;
     private ParteEnviada parteEnviada;
     private String numeroRemito;
     private String destinatario;
     private Date fechaEnvio;
     private String puntoPartida;
     private String puntoLlegada;

    public GrEnvio() {
    }

    public GrEnvio(ParteEnviada parteEnviada, String numeroRemito, String destinatario, Date fechaEnvio, String puntoPartida, String puntoLlegada) {
       this.parteEnviada = parteEnviada;
       this.numeroRemito = numeroRemito;
       this.destinatario = destinatario;
       this.fechaEnvio = fechaEnvio;
       this.puntoPartida = puntoPartida;
       this.puntoLlegada = puntoLlegada;
    }
   
    public Integer getCodGrEnvio() {
        return this.codGrEnvio;
    }
    
    public void setCodGrEnvio(Integer codGrEnvio) {
        this.codGrEnvio = codGrEnvio;
    }
    public ParteEnviada getParteEnviada() {
        return this.parteEnviada;
    }
    
    public void setParteEnviada(ParteEnviada parteEnviada) {
        this.parteEnviada = parteEnviada;
    }
    public String getNumeroRemito() {
        return this.numeroRemito;
    }
    
    public void setNumeroRemito(String numeroRemito) {
        this.numeroRemito = numeroRemito;
    }
    public String getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public String getPuntoPartida() {
        return this.puntoPartida;
    }
    
    public void setPuntoPartida(String puntoPartida) {
        this.puntoPartida = puntoPartida;
    }
    public String getPuntoLlegada() {
        return this.puntoLlegada;
    }
    
    public void setPuntoLlegada(String puntoLlegada) {
        this.puntoLlegada = puntoLlegada;
    }




}


