package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * IncidenciaHasEstadoId generated by hbm2java
 */
public class IncidenciaHasEstadoId  implements java.io.Serializable {


     private int codIncidencia;
     private int codEstado;

    public IncidenciaHasEstadoId() {
    }

    public IncidenciaHasEstadoId(int codIncidencia, int codEstado) {
       this.codIncidencia = codIncidencia;
       this.codEstado = codEstado;
    }
   
    public int getCodIncidencia() {
        return this.codIncidencia;
    }
    
    public void setCodIncidencia(int codIncidencia) {
        this.codIncidencia = codIncidencia;
    }
    public int getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(int codEstado) {
        this.codEstado = codEstado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IncidenciaHasEstadoId) ) return false;
		 IncidenciaHasEstadoId castOther = ( IncidenciaHasEstadoId ) other; 
         
		 return (this.getCodIncidencia()==castOther.getCodIncidencia())
 && (this.getCodEstado()==castOther.getCodEstado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodIncidencia();
         result = 37 * result + this.getCodEstado();
         return result;
   }   


}


