package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * IncidenciaHasEstado generated by hbm2java
 */
public class IncidenciaHasEstado  implements java.io.Serializable {


     private IncidenciaHasEstadoId id;
     private Estado estado;
     private Incidencia incidencia;
     private Date fechaActualizacionEstado;

    public IncidenciaHasEstado() {
    }

    public IncidenciaHasEstado(IncidenciaHasEstadoId id, Estado estado, Incidencia incidencia, Date fechaActualizacionEstado) {
       this.id = id;
       this.estado = estado;
       this.incidencia = incidencia;
       this.fechaActualizacionEstado = fechaActualizacionEstado;
    }
   
    public IncidenciaHasEstadoId getId() {
        return this.id;
    }
    
    public void setId(IncidenciaHasEstadoId id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Incidencia getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(Incidencia incidencia) {
        this.incidencia = incidencia;
    }
    public Date getFechaActualizacionEstado() {
        return this.fechaActualizacionEstado;
    }
    
    public void setFechaActualizacionEstado(Date fechaActualizacionEstado) {
        this.fechaActualizacionEstado = fechaActualizacionEstado;
    }




}


