package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private String codLocation;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String email;
     private String telefono;
     private String celular;
     private Set<ClienteNatural> clienteNaturals = new HashSet<ClienteNatural>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Location() {
    }

	
    public Location(String codLocation, String nombre, String email) {
        this.codLocation = codLocation;
        this.nombre = nombre;
        this.email = email;
    }
    public Location(String codLocation, String nombre, String apellidoPaterno, String apellidoMaterno, String email, String telefono, String celular, Set<ClienteNatural> clienteNaturals, Set<Factura> facturas, Set<Trabajador> trabajadors, Set<Empresa> empresas) {
       this.codLocation = codLocation;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.email = email;
       this.telefono = telefono;
       this.celular = celular;
       this.clienteNaturals = clienteNaturals;
       this.facturas = facturas;
       this.trabajadors = trabajadors;
       this.empresas = empresas;
    }
   
    public String getCodLocation() {
        return this.codLocation;
    }
    
    public void setCodLocation(String codLocation) {
        this.codLocation = codLocation;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Set<ClienteNatural> getClienteNaturals() {
        return this.clienteNaturals;
    }
    
    public void setClienteNaturals(Set<ClienteNatural> clienteNaturals) {
        this.clienteNaturals = clienteNaturals;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


