package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer codMarca;
     private String nombreMarca;
     private Set<Modelo> modelos = new HashSet<Modelo>(0);

    public Marca() {
    }

	
    public Marca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public Marca(String nombreMarca, Set<Modelo> modelos) {
       this.nombreMarca = nombreMarca;
       this.modelos = modelos;
    }
   
    public Integer getCodMarca() {
        return this.codMarca;
    }
    
    public void setCodMarca(Integer codMarca) {
        this.codMarca = codMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public Set<Modelo> getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set<Modelo> modelos) {
        this.modelos = modelos;
    }




}


