package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private Integer codModelo;
     private Marca marca;
     private String nombreModelo;
     private double precio;
     private Set<Certificado> certificados = new HashSet<Certificado>(0);
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Modelo() {
    }

	
    public Modelo(Marca marca, String nombreModelo, double precio) {
        this.marca = marca;
        this.nombreModelo = nombreModelo;
        this.precio = precio;
    }
    public Modelo(Marca marca, String nombreModelo, double precio, Set<Certificado> certificados, Set<Equipo> equipos) {
       this.marca = marca;
       this.nombreModelo = nombreModelo;
       this.precio = precio;
       this.certificados = certificados;
       this.equipos = equipos;
    }
   
    public Integer getCodModelo() {
        return this.codModelo;
    }
    
    public void setCodModelo(Integer codModelo) {
        this.codModelo = codModelo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getNombreModelo() {
        return this.nombreModelo;
    }
    
    public void setNombreModelo(String nombreModelo) {
        this.nombreModelo = nombreModelo;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set<Certificado> getCertificados() {
        return this.certificados;
    }
    
    public void setCertificados(Set<Certificado> certificados) {
        this.certificados = certificados;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


