package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private Integer codNota;
     private Incidencia incidencia;
     private int numeroSecuencia;
     private Date fecha;
     private Date time;
     private String descripcion;

    public Nota() {
    }

    public Nota(Incidencia incidencia, int numeroSecuencia, Date fecha, Date time, String descripcion) {
       this.incidencia = incidencia;
       this.numeroSecuencia = numeroSecuencia;
       this.fecha = fecha;
       this.time = time;
       this.descripcion = descripcion;
    }
   
    public Integer getCodNota() {
        return this.codNota;
    }
    
    public void setCodNota(Integer codNota) {
        this.codNota = codNota;
    }
    public Incidencia getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(Incidencia incidencia) {
        this.incidencia = incidencia;
    }
    public int getNumeroSecuencia() {
        return this.numeroSecuencia;
    }
    
    public void setNumeroSecuencia(int numeroSecuencia) {
        this.numeroSecuencia = numeroSecuencia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


