package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * Nrp generated by hbm2java
 */
public class Nrp  implements java.io.Serializable {


     private String partNumber;
     private String descripcion;

    public Nrp() {
    }

	
    public Nrp(String partNumber) {
        this.partNumber = partNumber;
    }
    public Nrp(String partNumber, String descripcion) {
       this.partNumber = partNumber;
       this.descripcion = descripcion;
    }
   
    public String getPartNumber() {
        return this.partNumber;
    }
    
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


