package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParteDevuelta generated by hbm2java
 */
public class ParteDevuelta  implements java.io.Serializable {


     private Integer codParteDevuelta;
     private Incidencia incidencia;
     private String partNumber;
     private String nombreParte;
     private String estado;
     private String dps;
     private Date fechaRetorno;
     private Set<GrDevolucion> grDevolucions = new HashSet<GrDevolucion>(0);

    public ParteDevuelta() {
    }

	
    public ParteDevuelta(Incidencia incidencia, String partNumber, String nombreParte, String estado, String dps) {
        this.incidencia = incidencia;
        this.partNumber = partNumber;
        this.nombreParte = nombreParte;
        this.estado = estado;
        this.dps = dps;
    }
    public ParteDevuelta(Incidencia incidencia, String partNumber, String nombreParte, String estado, String dps, Date fechaRetorno, Set<GrDevolucion> grDevolucions) {
       this.incidencia = incidencia;
       this.partNumber = partNumber;
       this.nombreParte = nombreParte;
       this.estado = estado;
       this.dps = dps;
       this.fechaRetorno = fechaRetorno;
       this.grDevolucions = grDevolucions;
    }
   
    public Integer getCodParteDevuelta() {
        return this.codParteDevuelta;
    }
    
    public void setCodParteDevuelta(Integer codParteDevuelta) {
        this.codParteDevuelta = codParteDevuelta;
    }
    public Incidencia getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(Incidencia incidencia) {
        this.incidencia = incidencia;
    }
    public String getPartNumber() {
        return this.partNumber;
    }
    
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }
    public String getNombreParte() {
        return this.nombreParte;
    }
    
    public void setNombreParte(String nombreParte) {
        this.nombreParte = nombreParte;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDps() {
        return this.dps;
    }
    
    public void setDps(String dps) {
        this.dps = dps;
    }
    public Date getFechaRetorno() {
        return this.fechaRetorno;
    }
    
    public void setFechaRetorno(Date fechaRetorno) {
        this.fechaRetorno = fechaRetorno;
    }
    public Set<GrDevolucion> getGrDevolucions() {
        return this.grDevolucions;
    }
    
    public void setGrDevolucions(Set<GrDevolucion> grDevolucions) {
        this.grDevolucions = grDevolucions;
    }




}


