package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parte generated by hbm2java
 */
public class Parte  implements java.io.Serializable {


     private Integer codParte;
     private Componente componente;
     private String numeroSerie;
     private Set<ParteEnviada> parteEnviadas = new HashSet<ParteEnviada>(0);

    public Parte() {
    }

	
    public Parte(Componente componente, String numeroSerie) {
        this.componente = componente;
        this.numeroSerie = numeroSerie;
    }
    public Parte(Componente componente, String numeroSerie, Set<ParteEnviada> parteEnviadas) {
       this.componente = componente;
       this.numeroSerie = numeroSerie;
       this.parteEnviadas = parteEnviadas;
    }
   
    public Integer getCodParte() {
        return this.codParte;
    }
    
    public void setCodParte(Integer codParte) {
        this.codParte = codParte;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Set<ParteEnviada> getParteEnviadas() {
        return this.parteEnviadas;
    }
    
    public void setParteEnviadas(Set<ParteEnviada> parteEnviadas) {
        this.parteEnviadas = parteEnviadas;
    }




}


