package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParteEnviada generated by hbm2java
 */
public class ParteEnviada  implements java.io.Serializable {


     private Integer codParteEnviada;
     private Incidencia incidencia;
     private Parte parte;
     private String estado;
     private String dps;
     private Date fechaEnvio;
     private Set<GrEnvio> grEnvios = new HashSet<GrEnvio>(0);

    public ParteEnviada() {
    }

	
    public ParteEnviada(Incidencia incidencia, Parte parte, String estado, String dps) {
        this.incidencia = incidencia;
        this.parte = parte;
        this.estado = estado;
        this.dps = dps;
    }
    public ParteEnviada(Incidencia incidencia, Parte parte, String estado, String dps, Date fechaEnvio, Set<GrEnvio> grEnvios) {
       this.incidencia = incidencia;
       this.parte = parte;
       this.estado = estado;
       this.dps = dps;
       this.fechaEnvio = fechaEnvio;
       this.grEnvios = grEnvios;
    }
   
    public Integer getCodParteEnviada() {
        return this.codParteEnviada;
    }
    
    public void setCodParteEnviada(Integer codParteEnviada) {
        this.codParteEnviada = codParteEnviada;
    }
    public Incidencia getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(Incidencia incidencia) {
        this.incidencia = incidencia;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDps() {
        return this.dps;
    }
    
    public void setDps(String dps) {
        this.dps = dps;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Set<GrEnvio> getGrEnvios() {
        return this.grEnvios;
    }
    
    public void setGrEnvios(Set<GrEnvio> grEnvios) {
        this.grEnvios = grEnvios;
    }




}


