package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer codPerfil;
     private String nombrePerfil;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public Perfil() {
    }

	
    public Perfil(String nombrePerfil) {
        this.nombrePerfil = nombrePerfil;
    }
    public Perfil(String nombrePerfil, Set<Trabajador> trabajadors) {
       this.nombrePerfil = nombrePerfil;
       this.trabajadors = trabajadors;
    }
   
    public Integer getCodPerfil() {
        return this.codPerfil;
    }
    
    public void setCodPerfil(Integer codPerfil) {
        this.codPerfil = codPerfil;
    }
    public String getNombrePerfil() {
        return this.nombrePerfil;
    }
    
    public void setNombrePerfil(String nombrePerfil) {
        this.nombrePerfil = nombrePerfil;
    }
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


