package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int codProvincia;
     private Departamento departamento;
     private String nombreProvincia;
     private Set<Distrito> distritos = new HashSet<Distrito>(0);

    public Provincia() {
    }

	
    public Provincia(int codProvincia, Departamento departamento, String nombreProvincia) {
        this.codProvincia = codProvincia;
        this.departamento = departamento;
        this.nombreProvincia = nombreProvincia;
    }
    public Provincia(int codProvincia, Departamento departamento, String nombreProvincia, Set<Distrito> distritos) {
       this.codProvincia = codProvincia;
       this.departamento = departamento;
       this.nombreProvincia = nombreProvincia;
       this.distritos = distritos;
    }
   
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreProvincia() {
        return this.nombreProvincia;
    }
    
    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }




}


