package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SlaIncidencia generated by hbm2java
 */
public class SlaIncidencia  implements java.io.Serializable {


     private Integer codSlaIncidencia;
     private String abreviaturaSlaIncidencia;
     private String descripcionSlaIncidencia;
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

    public SlaIncidencia() {
    }

	
    public SlaIncidencia(String abreviaturaSlaIncidencia, String descripcionSlaIncidencia) {
        this.abreviaturaSlaIncidencia = abreviaturaSlaIncidencia;
        this.descripcionSlaIncidencia = descripcionSlaIncidencia;
    }
    public SlaIncidencia(String abreviaturaSlaIncidencia, String descripcionSlaIncidencia, Set<Incidencia> incidencias) {
       this.abreviaturaSlaIncidencia = abreviaturaSlaIncidencia;
       this.descripcionSlaIncidencia = descripcionSlaIncidencia;
       this.incidencias = incidencias;
    }
   
    public Integer getCodSlaIncidencia() {
        return this.codSlaIncidencia;
    }
    
    public void setCodSlaIncidencia(Integer codSlaIncidencia) {
        this.codSlaIncidencia = codSlaIncidencia;
    }
    public String getAbreviaturaSlaIncidencia() {
        return this.abreviaturaSlaIncidencia;
    }
    
    public void setAbreviaturaSlaIncidencia(String abreviaturaSlaIncidencia) {
        this.abreviaturaSlaIncidencia = abreviaturaSlaIncidencia;
    }
    public String getDescripcionSlaIncidencia() {
        return this.descripcionSlaIncidencia;
    }
    
    public void setDescripcionSlaIncidencia(String descripcionSlaIncidencia) {
        this.descripcionSlaIncidencia = descripcionSlaIncidencia;
    }
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }




}


