package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer codSucursal;
     private Direccion direccion;
     private String telefono;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public Sucursal() {
    }

	
    public Sucursal(Direccion direccion, String telefono) {
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Sucursal(Direccion direccion, String telefono, Set<Trabajador> trabajadors) {
       this.direccion = direccion;
       this.telefono = telefono;
       this.trabajadors = trabajadors;
    }
   
    public Integer getCodSucursal() {
        return this.codSucursal;
    }
    
    public void setCodSucursal(Integer codSucursal) {
        this.codSucursal = codSucursal;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


