package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoIncidencia generated by hbm2java
 */
public class TipoIncidencia  implements java.io.Serializable {


     private Integer codTipoIncidencia;
     private String abreviacionTipoIncidencia;
     private String descripcionTipoIncidencia;
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

    public TipoIncidencia() {
    }

	
    public TipoIncidencia(String abreviacionTipoIncidencia, String descripcionTipoIncidencia) {
        this.abreviacionTipoIncidencia = abreviacionTipoIncidencia;
        this.descripcionTipoIncidencia = descripcionTipoIncidencia;
    }
    public TipoIncidencia(String abreviacionTipoIncidencia, String descripcionTipoIncidencia, Set<Incidencia> incidencias) {
       this.abreviacionTipoIncidencia = abreviacionTipoIncidencia;
       this.descripcionTipoIncidencia = descripcionTipoIncidencia;
       this.incidencias = incidencias;
    }
   
    public Integer getCodTipoIncidencia() {
        return this.codTipoIncidencia;
    }
    
    public void setCodTipoIncidencia(Integer codTipoIncidencia) {
        this.codTipoIncidencia = codTipoIncidencia;
    }
    public String getAbreviacionTipoIncidencia() {
        return this.abreviacionTipoIncidencia;
    }
    
    public void setAbreviacionTipoIncidencia(String abreviacionTipoIncidencia) {
        this.abreviacionTipoIncidencia = abreviacionTipoIncidencia;
    }
    public String getDescripcionTipoIncidencia() {
        return this.descripcionTipoIncidencia;
    }
    
    public void setDescripcionTipoIncidencia(String descripcionTipoIncidencia) {
        this.descripcionTipoIncidencia = descripcionTipoIncidencia;
    }
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }




}


