package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * TrabajadorHasCertificadoId generated by hbm2java
 */
public class TrabajadorHasCertificadoId  implements java.io.Serializable {


     private int codTrabajador;
     private int codCertificado;

    public TrabajadorHasCertificadoId() {
    }

    public TrabajadorHasCertificadoId(int codTrabajador, int codCertificado) {
       this.codTrabajador = codTrabajador;
       this.codCertificado = codCertificado;
    }
   
    public int getCodTrabajador() {
        return this.codTrabajador;
    }
    
    public void setCodTrabajador(int codTrabajador) {
        this.codTrabajador = codTrabajador;
    }
    public int getCodCertificado() {
        return this.codCertificado;
    }
    
    public void setCodCertificado(int codCertificado) {
        this.codCertificado = codCertificado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabajadorHasCertificadoId) ) return false;
		 TrabajadorHasCertificadoId castOther = ( TrabajadorHasCertificadoId ) other; 
         
		 return (this.getCodTrabajador()==castOther.getCodTrabajador())
 && (this.getCodCertificado()==castOther.getCodCertificado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodTrabajador();
         result = 37 * result + this.getCodCertificado();
         return result;
   }   


}


