package modelo;
// Generated Nov 19, 2015 3:42:42 PM by Hibernate Tools 4.3.1



/**
 * UsuarioHasModuloId generated by hbm2java
 */
public class UsuarioHasModuloId  implements java.io.Serializable {


     private int usuarioCodUsuario;
     private int moduloCodModulo;

    public UsuarioHasModuloId() {
    }

    public UsuarioHasModuloId(int usuarioCodUsuario, int moduloCodModulo) {
       this.usuarioCodUsuario = usuarioCodUsuario;
       this.moduloCodModulo = moduloCodModulo;
    }
   
    public int getUsuarioCodUsuario() {
        return this.usuarioCodUsuario;
    }
    
    public void setUsuarioCodUsuario(int usuarioCodUsuario) {
        this.usuarioCodUsuario = usuarioCodUsuario;
    }
    public int getModuloCodModulo() {
        return this.moduloCodModulo;
    }
    
    public void setModuloCodModulo(int moduloCodModulo) {
        this.moduloCodModulo = moduloCodModulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioHasModuloId) ) return false;
		 UsuarioHasModuloId castOther = ( UsuarioHasModuloId ) other; 
         
		 return (this.getUsuarioCodUsuario()==castOther.getUsuarioCodUsuario())
 && (this.getModuloCodModulo()==castOther.getModuloCodModulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioCodUsuario();
         result = 37 * result + this.getModuloCodModulo();
         return result;
   }   


}


